# Generated by Django 3.1.5 on 2021-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='kitchen',
            field=models.ManyToManyField(to='main.Kitchen'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
