# Generated by Django 3.1.5 on 2021-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210109_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
    ]
